### ISSUE TITLE
Automatic login for each test

### ISSUE THREAD

**Issue by dan-klasson** [elliterate/capybara.py#16]
I'd like to skip filling in the login form for each single test that requires authentication.

Is there an easy way to do this? I was checking out `session.fill_in("q", value="Capybara")`. But I can't seem to find any session available to me in the `dsl` object even though it states that `When using :mod:`capybara.dsl`, the Session is initialized automatically for you.`

What's a preferred method of doing this?

**Comment by elliterate** [comment]
A “session” in Capybara is a _browser_ session. This is different from the _user_ session that your application creates when a user logs in (or destroys when a user logs out). When Capybara initializes (or resets) a browser session, it merely initializes (or resets) the browser, putting it into a clean state for the next test. (Precisely what it does depends on the current driver. For example, with Selenium, that means deleting all cookies for the current domain and navigating to `about:blank`.)

Capybara only provides methods for interacting with a web page as a user would: visiting URLs, reading text, filling in form fields, and clicking buttons and links. It has no access to your application’s internals, including its session management. Skipping authentication for a test, then, depends entirely on your application. You would have to implement and expose a test-only hook that could be triggered by one or more of those basic user interactions (e.g., visiting a test-only URL that creates a user and corresponding session all at once).

Stepping back a bit, though, I’d encourage you to avoid doing this for as long as possible. I find that acceptance tests (i.e., those written using Capybara) are often most useful when they test fewer but longer end-to-end user workflows. They may include some common failures (e.g., an initially mistyped password), but aren’t the place to test every desired system behavior. With the larger, broader, more important workflows covered by acceptance tests, you can implement more fine-grained tests at the faster level of your classes and objects, rather than the slower level of the user interface. Then the slowness of logging in becomes less important, as it’s only being executed a handful of times.
